# golang alpine 1.15.3
FROM golang@sha256:6bdf3cc6cb0509e860e626a339c19b7e842efb8444960bb72d654e33607c34f5 as builder

RUN apk update && apk add --no-cache git ca-certificates tzdata make && update-ca-certificates

ENV USER=appuser
ENV UID=10001

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

WORKDIR $GOPATH/src/nani
COPY . .

ENV github="https://github.com/Melenium2/Nani.git"
ENV appname=Nani

RUN git clone ${github}
RUN make -C $appname deploy
RUN ls .
RUN cp -r ./$appname/config/prod.yml /go/bin/prod.yml
RUN cp -r ./$appname/config/schema.sql /go/bin/schema.sql
RUN cp -r ./bundles.txt /go/bin/bundles.txt
RUN mkdir /cache
#
RUN rm /go/bin/$appname
#
RUN ls /go/bin

WORKDIR /go/bin

CMD ["/go/bin/main", "-config", "prod.yml", "-schema", "schema.sql", "-cache", "/cache/cache.json", "-e", "bundles.txt"]