version: '3.7'
services:
    nani:
        build: .
        container_name: nani
        volumes:
            - /usr/volumes/bundles.txt:/go/bin/bundles.txt
            - /usr/volumes/cache.json:/go/bin/cache.json
