version: '3.7'
services:
    nani:
        build: .
        container_name: nani
        environment:
            - api_key=${API_KEY}
            - db_pass=${DB_PASS}
            - db_user=${DB_USER}
